# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 450)
        Form.setMinimumSize(QtCore.QSize(500, 450))
        Form.setMaximumSize(QtCore.QSize(500, 450))
        Form.setStyleSheet("QWidget#Form{\n"
"border-image: url(:/register/images/register_background.jpg);\n"
"}")
        self.main_menue_btn = QtWidgets.QPushButton(Form)
        self.main_menue_btn.setGeometry(QtCore.QRect(20, 30, 40, 45))
        self.main_menue_btn.setMinimumSize(QtCore.QSize(35, 35))
        self.main_menue_btn.setMaximumSize(QtCore.QSize(45, 45))
        self.main_menue_btn.setStyleSheet("QPushButton{\n"
"    border-radius:20px;\n"
"    background-color:rgb(255, 170, 127);\n"
"    border:2px solid rgb(250,218,218);\n"
"    color:white;\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    border:rgb(255,192,167);\n"
"}\n"
"QPushButton:checked{\n"
"    background-color:rgb(209,0,209);\n"
"}")
        self.main_menue_btn.setCheckable(True)
        self.main_menue_btn.setObjectName("main_menue_btn")
        self.exit_menue_btn = QtWidgets.QPushButton(Form)
        self.exit_menue_btn.setGeometry(QtCore.QRect(10, 100, 40, 45))
        self.exit_menue_btn.setMinimumSize(QtCore.QSize(35, 35))
        self.exit_menue_btn.setMaximumSize(QtCore.QSize(45, 45))
        self.exit_menue_btn.setStyleSheet("QPushButton{\n"
"    border-radius:20px;\n"
"    background-color:rgb(255, 170, 127);\n"
"    border:2px solid rgb(250,218,218);\n"
"    color:white;\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    border:rgb(255,192,167);\n"
"}\n"
"QPushButton:checked{\n"
"    background-color:rgb(209,0,209);\n"
"}")
        self.exit_menue_btn.setCheckable(False)
        self.exit_menue_btn.setObjectName("exit_menue_btn")
        self.reset_menue_btn = QtWidgets.QPushButton(Form)
        self.reset_menue_btn.setGeometry(QtCore.QRect(60, 70, 40, 45))
        self.reset_menue_btn.setMinimumSize(QtCore.QSize(35, 35))
        self.reset_menue_btn.setMaximumSize(QtCore.QSize(45, 45))
        self.reset_menue_btn.setStyleSheet("QPushButton{\n"
"    border-radius:20px;\n"
"    background-color:rgb(255, 170, 127);\n"
"    border:2px solid rgb(250,218,218);\n"
"    color:white;\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    border:rgb(255,192,167);\n"
"}\n"
"QPushButton:checked{\n"
"    background-color:rgb(209,0,209);\n"
"}")
        self.reset_menue_btn.setCheckable(False)
        self.reset_menue_btn.setObjectName("reset_menue_btn")
        self.about_menue_btn = QtWidgets.QPushButton(Form)
        self.about_menue_btn.setGeometry(QtCore.QRect(80, 10, 40, 45))
        self.about_menue_btn.setMinimumSize(QtCore.QSize(35, 35))
        self.about_menue_btn.setMaximumSize(QtCore.QSize(45, 45))
        self.about_menue_btn.setStyleSheet("QPushButton{\n"
"    border-radius:20px;\n"
"    background-color:rgb(255, 170, 127);\n"
"    border:2px solid rgb(250,218,218);\n"
"    color:white;\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    border:rgb(255,192,167);\n"
"}\n"
"QPushButton:checked{\n"
"    background-color:rgb(209,0,209);\n"
"}")
        self.about_menue_btn.setCheckable(False)
        self.about_menue_btn.setObjectName("about_menue_btn")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(160, 150, 211, 197))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setVerticalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setStyleSheet("color:rgb(204,204,204);\n"
"font:16pt \"方正舒体\";")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.account_le = QtWidgets.QLineEdit(self.layoutWidget)
        self.account_le.setMinimumSize(QtCore.QSize(0, 30))
        self.account_le.setStyleSheet("background-color:transparent;\n"
"color:rgb(240,240,240,240);\n"
"border:none;\n"
"border-bottom:1px solid lightgray;")
        self.account_le.setClearButtonEnabled(True)
        self.account_le.setObjectName("account_le")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.account_le)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setStyleSheet("color:rgb(204,204,204);\n"
"font:16pt \"方正舒体\";")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.password_le = QtWidgets.QLineEdit(self.layoutWidget)
        self.password_le.setMinimumSize(QtCore.QSize(0, 30))
        self.password_le.setStyleSheet("background-color:transparent;\n"
"color:rgb(240,240,240,240);\n"
"border:none;\n"
"border-bottom:1px solid lightgray;")
        self.password_le.setClearButtonEnabled(True)
        self.password_le.setObjectName("password_le")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.password_le)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setStyleSheet("color:rgb(204,204,204);\n"
"font:16pt \"方正舒体\";")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.confirm_pwd_le = QtWidgets.QLineEdit(self.layoutWidget)
        self.confirm_pwd_le.setMinimumSize(QtCore.QSize(0, 30))
        self.confirm_pwd_le.setStyleSheet("background-color:transparent;\n"
"color:rgb(240,240,240,240);\n"
"border:none;\n"
"border-bottom:1px solid lightgray;")
        self.confirm_pwd_le.setClearButtonEnabled(True)
        self.confirm_pwd_le.setObjectName("confirm_pwd_le")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.confirm_pwd_le)
        self.register_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.register_btn.setEnabled(False)
        self.register_btn.setMinimumSize(QtCore.QSize(0, 45))
        self.register_btn.setStyleSheet("QPushButton{\n"
"    background-color:rgb(255,170,127);\n"
"    color:rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color:rgb(197,197,197);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(255, 133, 111)\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(218,145,108);\n"
"}")
        self.register_btn.setCheckable(False)
        self.register_btn.setObjectName("register_btn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.register_btn)
        self.exit_menue_btn.raise_()
        self.reset_menue_btn.raise_()
        self.about_menue_btn.raise_()
        self.layoutWidget.raise_()
        self.main_menue_btn.raise_()

        self.retranslateUi(Form)
        self.main_menue_btn.clicked['bool'].connect(Form.show_hide_menue) # type: ignore
        self.about_menue_btn.clicked.connect(Form.about_menue) # type: ignore
        self.reset_menue_btn.clicked.connect(Form.reset_menue) # type: ignore
        self.exit_menue_btn.clicked.connect(Form.exit_menue) # type: ignore
        self.register_btn.clicked.connect(Form.check_register) # type: ignore
        self.account_le.textChanged['QString'].connect(Form.enable_register) # type: ignore
        self.password_le.textChanged['QString'].connect(Form.enable_register) # type: ignore
        self.confirm_pwd_le.textChanged['QString'].connect(Form.enable_register) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.main_menue_btn.setText(_translate("Form", "菜单"))
        self.exit_menue_btn.setText(_translate("Form", "退出"))
        self.reset_menue_btn.setText(_translate("Form", "重置"))
        self.about_menue_btn.setText(_translate("Form", "关于"))
        self.layoutWidget.setStyleSheet(_translate("Form", "QPushButton{\n"
"    background-color:rgb(255,170,127);\n"
"    color:rgb(75,60,182);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    border:rgb(255,192,167);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(218,145,108);\n"
"}"))
        self.label.setText(_translate("Form", "账   号:"))
        self.label_2.setText(_translate("Form", "密   码:"))
        self.label_3.setText(_translate("Form", "确认密码:"))
        self.register_btn.setText(_translate("Form", "注册"))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
